(use-package paredit)
(use-package cider)
(use-package clj-refactor)
(use-package ac-cider)
(use-package aggressive-indent)
(use-package rainbow-delimiters)
(use-package which-key)
(use-package markdown-mode)
(use-package markdown-mode+)
(use-package yaml-mode)
(use-package go-mode)
(use-package go-autocomplete)
(use-package go-eldoc)

(defun my-clojure-hook ()
  (paredit-mode 1)
  (clj-refactor-mode 1)
  (aggressive-indent-mode 1)
  (rainbow-delimiters-mode 1)
  (eldoc-mode 1)
  (put-clojure-indent 'fail-pipeline 1)
  (put-clojure-indent 'fail-let 1)
  (put-clojure-indent 'fail-if-let 1))

(add-hook 'cider-repl-mode-hook 'my-clojure-hook)
(add-hook 'clojure-mode-hook 'my-clojure-hook)

(which-key-mode)
